name: Coverage

on:
  push:
    branches: [main, release-*]
    paths-ignore:
      - "docs/**"
  pull_request:
    branches: [main, release-*]
    paths-ignore:
      - "docs/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@v1.10.0
      - name: Redis in GitHub Actions
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: 6
      - name: Prepare git config
        run: |
          git config --global user.email "gitstorage.bot@gluesql.org"
          git config --global user.name "GitStorage Bot"
      - run: rustup component add llvm-tools-preview
      - run: cargo install grcov
      - name: Install redis-cli
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-tools jq
      - name: clean
        run: |
          cargo clean
          rm -rf ./target/debug/deps/gluesql*
          find . -name '*.profraw' -delete
          cd storages/csv-storage && rm -rf ./tmp && cd ../..
          cd storages/json-storage && rm -rf ./tmp && cd ../..
          redis-cli flushall
      - name: build
        env:
          RUSTFLAGS: -Cinstrument-coverage
        run: cargo build --workspace --all-features --verbose
      - name: run coverage
        env:
          GIT_REMOTE: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        run: bash ./scripts/coverage.sh
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
